### ISSUE TITLE
dev20220310: TZ limited  to range [-12...+12]

### ISSUE THREAD

**Issue by W-Geronius** [norbert-walter/esp32-nmea2000-obp60#25]
but, have a look at our friends in Auckland (NZ) = UTC+13

![image](https://user-images.githubusercontent.com/18160302/157659290-cac7b57e-544a-4ee7-8290-3b036504ecb8.png)

Also subhour timezones should be possible, from -12h up to +13:45 and +14h  see https://www.timeanddate.de/zeitzonen/weltweit/

**Comment by norbert-walter** [comment]
There are a wide variety of time zones, including some with segments of an hour. We cannot support all time zones and limit ourselves to the full hour shift only. I will support -12...+14h. 

https://de.wikipedia.org/wiki/Datei:World_Time_Zones_Map.png
![TimeZones](https://user-images.githubusercontent.com/22027682/157682116-2e618d05-4b17-4a5f-b6a1-c7d84ba274a5.png)

**Comment by norbert-walter** [comment]
Solved in 20220311
