### ISSUE TITLE
dev20220309: Time Zones: change of date not calculated properly

### ISSUE THREAD

**Issue by W-Geronius** [norbert-walter/esp32-nmea2000-obp60#26]
Anchorage: -10h:  10.3. 05:50 UTC displays as **10.3. -5:50 LOT**
Fischi: +12h 10.3. 12.29 UTC displays as **10.3. 24:26 LOT**
watch out for leap years !

**Comment by norbert-walter** [comment]
Yes, that is not calculated.

**Comment by W-Geronius** [comment]
please check attached files. They hopefully fix LOT date & time calculation within the formatter and the clock page.

As an enhancement I enabled decimal fractions of hours to be processed.
This permits odd timeoffsets like ACWST, Australian Central Western Standardtime (UTC + 8:45)
The ACWST example would require to configure TZ 8.75.
To be added in documentation 

[fixIssue_26.zip](https://github.com/norbert-walter/esp32-nmea2000/files/8314224/fixIssue_26.zip)

NOTE: 
maybe a coincidence, maybe not: 
with these changes and page 1 set to clock: contrast of eInk display is very poor after reboot for the first couple of minutes

**Comment by norbert-walter** [comment]
Solved in 20220324
