### ISSUE TITLE
dev20220311: suggestion: restrict logging 'Drawing at ...' to log level DEBUG

### ISSUE THREAD

**Issue by W-Geronius** [norbert-walter/esp32-nmea2000-obp60#31]
not sure, if messages 'Drawing at Page...' and 'Ready status BME2080' should be seen at log level LOG. It's quite chatty.
Maybe better output this (very useful!) info at loglevel DEBUG.

**Comment by norbert-walter** [comment]
This information is on loglevel DEBUG.

**Comment by W-Geronius** [comment]
ups, I was wrong - I thought it was on default log level (ERROR). In fact it's shown on level LOG, which is ok too

**Comment by norbert-walter** [comment]
Closed
