### ISSUE TITLE
v20220311: typo in display names list: fourValues

### ISSUE THREAD

**Issue by W-Geronius** [norbert-walter/esp32-nmea2000-obp60#32]
rename to '**fourValues**', according to naming convention 

![image](https://user-images.githubusercontent.com/18160302/158009462-fbe252f9-b277-4a4e-96a8-b525fc7c1eb5.png)

**Comment by norbert-walter** [comment]
I still want to revise all the names. Then I'll do it right away.

**Comment by norbert-walter** [comment]
Solved in 20220313
