### ISSUE TITLE
v20220311 typo in Help text: should be 'Battery capacity'

### ISSUE THREAD

**Issue by W-Geronius** [norbert-walter/esp32-nmea2000-obp60#33]
![image](https://user-images.githubusercontent.com/18160302/158010290-d82b50a8-8600-4dd4-a850-ce40d44b1996.png)

**Comment by W-Geronius** [comment]
there are quite some other typos in help texts. Better postpone fix, until tests completed. I could also provide a corrected config.json upon request

**Comment by norbert-walter** [comment]
Please make a full update or refresh the browser cach. I cold not see the problems in the actual firmware on this position. Or you use the old config.json.

**Comment by norbert-walter** [comment]
Solved in 20220313
