### ISSUE TITLE
suggestion to change logic of GPS and Bus Data LED

### ISSUE THREAD

**Issue by W-Geronius** [norbert-walter/esp32-nmea2000-obp60#35]
**no GPS/ no Fix : turn LED on**
GPS/Fix : turn LED off

**Bus data  missing: turn LED on**
Bus data present: turn LED off

1) a LED lit in bright RED is drawing more attention than a LED unlit and generally implies: WARNING
2) in the case of 'limits' the LED serves as warning too
3) a permanently lit LED might be uncomfortable at night, LED unlit should be the default in the dark

**Comment by norbert-walter** [comment]
Solved in 20220313
