### ISSUE TITLE
dev20220314 QR WiFi not working

### ISSUE THREAD

**Issue by W-Geronius** [norbert-walter/esp32-nmea2000-obp60#40]
In normal display mode, QR is recognized (SSID at least), but no login possible.
In inverse mode, QR is not recognized at all
Apart from that: QR code display time may be too short ...

**Comment by norbert-walter** [comment]
Both versions work for me in normal and inverse display. Both with SSID and password. The QR code is constructed with 33x33 pixels with the lowest error correction. A total of 77 alphanumeric characters can thus be transmitted. That should be enough for SSID and password. However, there are a number of apps that cannot handle an inverse display of the QR code. But that's a problem with the app. I use the "QR scanner" on Android 11. Also, starting with Android 9, the WiFi settings are no longer automatically activated. You then always have to insert the password manually with copy & paste and explicitly release the configuration.

**Comment by W-Geronius** [comment]
Thanks, I could verify both QR are working correctly when using another [QR scanning app](https://play.google.com/store/apps/details?id=com.scannerapp.qrcodereader)
