### ISSUE TITLE
dev20220314 GPSD and GPST displaying LOT ?

### ISSUE THREAD

**Issue by W-Geronius** [norbert-walter/esp32-nmea2000-obp60#41]
If a timezone is defined, GPSD and GPST display LOT. 
Shouldn't they always be UTC time? Maybe new values local date & local time LOD/LOT should be selectable separately

**Comment by norbert-walter** [comment]
When a time zone is defined, GPSD and GPST always show LOT. You also move in the local time. LOT only indicates that the time displayed is not UTC time. The formatter does the conversion to local time. The WebUI is used to determine which time zone you are in. This then applies to the time and date specification. You could also create a special user page that only displays the UTC time. I still wanted to do something like that.

**Comment by W-Geronius** [comment]
Naming of GPSD and GPST is inconsistent then in regards to the nmea2000 gateway display. On OBP60 they don't reflect GPS date/time (unless you are in TZ 0)

**Comment by norbert-walter** [comment]
Thats correct. The data in WebUÍ are always UTC time. The time zone only working for the OBP pages.
