### ISSUE TITLE
v20220320: avoid logging inactive devices

### ISSUE THREAD

**Issue by W-Geronius** [norbert-walter/esp32-nmea2000-obp60#50]
![image](https://user-images.githubusercontent.com/18160302/159157265-e5d17e53-64d2-4a18-a4ea-da68c64c772f.png)
cosmetic:
when logging is set to 'LOG', **devices deactivated per configuration** should not output LOG records
like BME280 (line 689 in obp60task.cpp) and rotation sensor (line 761 in obp60task.cpp)

**Comment by norbert-walter** [comment]
Solved in 20220320
