### ISSUE TITLE
OBP60 hardware: LED pairs flickering at random

### ISSUE THREAD

**Issue by W-Geronius** [norbert-walter/esp32-nmea2000-obp60#60]
At random occasions backlight  LEDs (pairs) were either slightly dimmed or started flickering. Resoldering the right 2 LED + resistor + transistor possibly cured the problem and for a couple of days no further problems were observed.

This morning however, the two leftmost LED started flickering. Cold reboot temporarily solved it. Now the middle two LED are slightly dimmed, the leftmost two minimally flickering, the right two are still perfect.

**Comment by W-Geronius** [comment]
are you sure, flickering is totally unaffected by software? First time now I am observing all 6 LEDs flickering - all at the same rate, could be a pattern.

**Comment by W-Geronius** [comment]
> First time now I am observing all 6 LEDs flickering - all at the same rate, could be a pattern.

Scratch that, sorry!

Simple solution: looked like too little power and so it was ...
maybe add this to docs!  However, the display runs surprisingly well under these circumstances!

The display was powered solely via PC USB port:

![image](https://user-images.githubusercontent.com/18160302/163775382-cb702d93-c387-45d3-badc-3f80e66d0ea5.png)

btw: 
the PC USB delivers ~5V, just 3.4V are displayed here ?

**Comment by norbert-walter** [comment]
Yes, you can not powering the MFD via USB. Any ports supports only 500mA and the voltage loss is to big. Use allways 12V for powering.
