### ISSUE TITLE
FW upgrade/downgrade - config storage (non volatile storage) corruption

### ISSUE THREAD

**Issue by W-Geronius** [norbert-walter/esp32-nmea2000-obp60#61]
When upgrading (or downgrading) firmware a nvs corruption may happen. Apart from complete failure, this might express itself by OBP60 configuration entries missing from the web interface. It is not entirely clear yet, what's the best ways to recover.
A complete flash (nodemcu32s_obp60-all.bin) **may not reliably solve the problem**

Solutions tried: 
* 'Firmware reset' via web config page, 
* upload using platformio (this is usually just a simple update), 
* flash using ESP32N2K-Flasher, 
* configure from scratch (restore configuration should be applied with great care)

Some effort is required to further explore the problems & document failsafe recovery procedures. 
Standard tests should be defined and established for production releases

**Comment by norbert-walter** [comment]
A downgrade must always be performed with an initial firmware so that the configuration remains consistent.
