### ISSUE TITLE
E-Paper display fades when exposed to SUN

### ISSUE THREAD

**Issue by W-Geronius** [norbert-walter/esp32-nmea2000-obp60#68]
Exposed to plain sun the display fades very quickly. As discussed before, a more effective UV/IR protection filter should be attached. For test purposes I ordered a free sample of https://www.semasorb.com/produkt/uva-sonnenschutzfolie-semasorb-dk400/ - I'll report about that

> _[The e-ink screen is recommended for indoor use. If it is used outdoors, it is necessary to avoid direct sunlight on the e-ink screen, and at the same time, take UV protection measures, **because charged particles will dry out under strong light for a long time, resulting in loss of activity and failure to refresh. This situation is irreversible.** When designing e-ink screen products, customers should pay attention to determine whether the use environment meets the requirements of e-ink screen](https://www.waveshare.com/wiki/4.2inch_e-Paper_Module)_

Even the 'full refresh' (seemingly consisting of 2 consecutive redraws) doesn't improve display quality - while the first redraw restores normal contrast, the second (and final redraw) even decreases contrast. Attached video demonstrates that effect: refresh events occur at 10:55:49 and 11:05:49

Strange enough, the lower part of the screen appears to be less affected by decrease of contrast - it somehow looks like it 'recovers' from its extremely poor readability right after refresh.

To meet github max filesize (10MB) the video is optimized to minimal size and plays at 2x speed:

https://user-images.githubusercontent.com/18160302/172000047-2dcbc7e0-3172-4a29-9523-7eaf7e4ad943.mp4

[OBP60 Display UV.mp4 zipped](https://github.com/norbert-walter/esp32-nmea2000/files/8837743/OBP60.Display.UV.zip)

Original video (~500MB, although not perfect too) is available upon request

The device was exposed to sun, quite hazy though - under clear sun condition the display fades even more quickly

**Comment by W-Geronius** [comment]
reminder from threema conversation 
![image](https://user-images.githubusercontent.com/18160302/173182912-66ff82ae-8429-4780-a945-4f71702b5af4.png)

**Comment by W-Geronius** [comment]
reminder to threema conversation:
![threema-20220624-115925547](https://user-images.githubusercontent.com/18160302/175522362-54e14cd8-18d4-4315-a386-0672ec7663e0.jpg)

promising results using IR filters

**Comment by norbert-walter** [comment]
IR radiation ist the problem on the display. The IR radiation heating up the black pixel and reducing the viscosity of gel layer between the glases. To resolf the problem we can using sunshine protection foil with UV and IR blocker. Several manufacturer has helpfully products. Products from 3M are the best.

Refer the resultrs:

Without protection: https://www.youtube.com/watch?v=m_Ud9td2hmo
With protection: https://www.youtube.com/watch?v=_o3J9punhgE
