### ISSUE TITLE
dev20220620: clock page: clock hands set to 14:00 if no time present

### ISSUE THREAD

**Issue by W-Geronius** [norbert-walter/esp32-nmea2000-obp60#69]
![IMG_20220624_125135](https://user-images.githubusercontent.com/18160302/175521324-5607df4e-0f1e-4397-85ed-681b9611c43f.jpg)

whith 'hold' set to true, but no time was available since boot, there are no 'old' values to display.
In this case also the clock hands should be hidden

In addition: the literal SunR is missing,   excessive "---"

**Comment by norbert-walter** [comment]
Solved in 20220626
