### ISSUE TITLE
dev20220528: DTW (distance to waypoint) not displaying continously but showing intermittent '---'

### ISSUE THREAD

**Issue by W-Geronius** [norbert-walter/esp32-nmea2000-obp60#70]
see attached video

setup: display is connected to AvNav running on raspberry. 
AvNav webpage displays DTW continously in browser view 

https://user-images.githubusercontent.com/18160302/177607537-0f809f70-d723-479e-ab88-ef78f4c6e250.mp4

**Comment by norbert-walter** [comment]
We must contact Andreas for this problem.

**Comment by wellenvogel** [comment]
Can you check the router settings in AvNav?
By default RMB is potentialky only send every 5s.
But the display has 4s timeout for the values.
Just set the RMB interval to e.g. 1s in AvNav.

**Comment by norbert-walter** [comment]
Where can I put the value?

**Comment by W-Geronius** [comment]
![image](https://user-images.githubusercontent.com/18160302/179744932-aed79012-9ace-4eaf-b3a0-fe517d9972dc.png)

At present I have no working system at hand - I'll check that asap. Promising idea

**Comment by norbert-walter** [comment]
I think this solve the problem.

**Comment by W-Geronius** [comment]
> Can you check the router settings in AvNav? By default RMB is potentialky only send every 5s. But the display has 4s timeout for the values. Just set the RMB interval to e.g. 1s in AvNav.

Setting RMB interval to 3s does indeed solve the problem. Thanks
