### ISSUE TITLE
dev20220528: TWD not correct

### ISSUE THREAD

**Issue by W-Geronius** [norbert-walter/esp32-nmea2000-obp60#71]
![PXL_20220630_202249707 r](https://user-images.githubusercontent.com/18160302/177608837-3828e09e-22d7-402e-af0e-bc26ea9eada2.jpg)

most of the times when I checked TWD, it's value was above 360°

**Comment by norbert-walter** [comment]
I think the angle calculation is wrong. I chek it.

**Comment by norbert-walter** [comment]
Is fixed from thooge
