### ISSUE TITLE
XTE formatting and default formatting of negative numbers

### ISSUE THREAD

**Issue by W-Geronius** [norbert-walter/esp32-nmea2000-obp60#72]
1.) OBP60Formatter.cpp lacks specific XTE handling  (like value->getFormat() == "formatXTE"). 
Therefore no unit is displayed for XTE values and formatting is left to default processing (lines 684ff)

2.) XTE = 0 is displayed as **-0.00**

3.) default processing formats negative values with 2 decimals, causing an overflow on display (e.g. in bottom fields of PageFourValues2)

**Comment by W-Geronius** [comment]
as a quick & dirty fix, default formatting could be modified:

> {
            if(value->value >= 100){
            snprintf(buffer,bsize,"%3.0f",value->value);
            } else if (value->value >= 10){
            snprintf(buffer,bsize,"%3.1f",value->value);
            } else if (value->value > 0){
            snprintf(buffer,bsize,"%3.2f",value->value);
            } else if (value->value > -10){
            snprintf(buffer,bsize,"%3.1f",value->value);
            } else {
            snprintf(buffer,bsize,"%3.0f",value->value);
            }

**Comment by W-Geronius** [comment]
possibly the dirty fix leads to this:
![image](https://user-images.githubusercontent.com/18160302/186637768-f18bc4a1-1fa8-45da-9eea-bf47fc932bc1.png)

![image](https://user-images.githubusercontent.com/18160302/186637915-88916722-90cd-402f-89af-6fe5650613f3.png)

odd XTE value !

to be investigated

**Comment by norbert-walter** [comment]
Good idea
