### ISSUE TITLE
Power Supply via USB-C

### ISSUE THREAD

**Issue by W-Geronius** [norbert-walter/esp32-nmea2000-obp60#78]
In chapters ‘Historie’ and 'Busssysteme USB', the documentation mentions that the device can be supplied with power via the USB-C connection. This option is not listed in the ‘Power supply’ chapter. The topic should be covered in more detail there, including the note that this option should only be used for test, demo or configuration purposes, but not for productive use. It is also not guaranteed that every power supply unit and every USB-C cable will be able to even boot the device. It works reasonably well with the Raspberry 4 power supply unit, which supplies a voltage of around 5.2V.

**Comment by norbert-walter** [comment]
The reliability of the power supply via USB-C depends crucially on the device that supplies the power. The quality of the cable also has an influence. Unfortunately, many devices cannot supply the required current for the OBP60 and cables often have a cross-section that is too small to supply enough power.

Therefore, I do not recommend power supply via USB-C. You should always use 12V as a power supply. If a power supply works reliably via USB-C, it can be used. In many cases, however, this is not the case. Even if the OBP60 initially appears to be working, problems can arise later when the power requirement is higher. This creates errors that are difficult to understand.

**Comment by norbert-walter** [comment]
Closed
