### ISSUE TITLE
OBP60 V2: sporadic reboots and rare partial freezing of display

### ISSUE THREAD

**Issue by W-Geronius** [norbert-walter/esp32-nmea2000-obp60#81]
Reboots and system hangs occur sporadically. This can also be observed with a completely original setup (out of the box, standalone)
Reboots are frequent, several within one day. Occasionally (1 to 2 times per day) the system crashes partially: the display freezes, will not updated. Buttons and buzzer continue to work (wipe, keylock - not sure about illum). The flashing LED inside the housing suggests that the GPS module is still working as well.

To facilitate joint troubleshooting, all observations and tests should be collected here.

**Comment by W-Geronius** [comment]
it appears that reboots occur more when frequently, when AP is active - could also be observed on OBP60 V1

**Comment by norbert-walter** [comment]
The cause of the firmware crashes is very complex, as 2 CPUs are used with multiple tasks. The causes have not been located at the moment. There are many indications that the problems are related to data traffic over WiFi. As a result, some tasks crash and the device is only partially functional. Firmware recovery is also affected. In some cases, the flash memory is corrupted and parts of the settings are lost. Firmware recovery is then only possible via USB-C.

**Comment by Unoxa** [comment]
Could a workaround be possible? My guess is that not all users need Wifi after configuring the OBP60. Is it possible to make Wifi active after every reboot for a period (30 min) to enable configuration  with a choice to either keep it on continiously or have it shutdown after 30 min? If Wifi is associated with the crashes, disabling Wifi might make the OBP60 more stable.

**Comment by norbert-walter** [comment]
This function is already implemented in the firmware. Under Config - System, a time period for the access point can be defined (stopApTime). The value is given in seconds and defines how long the access point should be active after a start. Test the function and check whether the error is then reduced. Please let us know the result.

Please refer the documentation: https://obp60-v2-docu.readthedocs.io/de/latest/usermanual/configuration.html#config-system

**Comment by Unoxa** [comment]
Thanks, I will try that and report back. Won’t be on the boat for two weeks
now but after that.

ons 7 aug. 2024 kl. 23:13 skrev Norbert Walter ***@***.***>:

**Comment by norbert-walter** [comment]
I turned off the WiFi after a while. The crashes stopped. Apparently this is a temporary solution.

**Comment by norbert-walter** [comment]
Fixed in dev20240920
