### ISSUE TITLE
Document improvement: additional Info to be added to chapter 'webflashtool'

### ISSUE THREAD

**Issue by W-Geronius** [norbert-walter/esp32-nmea2000-obp60#83]
**Trennen Sie das OBP60 von der Stromversorgung.** Öffnen Sie die hintere Gehäuseabdeckung und stellen Sie mit der Drahtbrücke eine Verbindung von GND (CN2) zum Pin 27 (ESP32-S3) her. **Stellen Sie die Stromversorgung wieder her - das OBP60 startet nun nicht wie gewohnt und gibt auch keinen Beeplaut von sich. Mit weiterhin bestehender Brücke verbinden Sie dann** das OBP60 mit dem PC über das USB-Verbindungskabel. Sobald sie USB-Schnittstelle erkannt wird, erfolgt eine Tonausgabe auf dem PC.

**Comment by norbert-walter** [comment]
In the meantime, I have changed the documentation in some places, but not in the suggested wording.

**Comment by norbert-walter** [comment]
Is implemented
