### ISSUE TITLE
dev20240920: Flash LED Mode 'GPS fix lost' stopped working

### ISSUE THREAD

**Issue by W-Geronius** [norbert-walter/esp32-nmea2000-obp60#88]
Flash LED Mode 'GPS fix lost' stopped working. 

setup: 
internal GPS deactivated, GPS data fed via WiFi (AvNav/SignalK)
stopping GPS doesn't trigger LED anymore

**Comment by norbert-walter** [comment]
The LED indicator is only working for internal hardware GPS and not working for external GPS data. This is not a bug.

**Comment by W-Geronius** [comment]
For OBP60 V1 this setting causes the LED to flash, when no GPS data are received. It serves extremely well as indicator for a broken wifi-connection - not an uncommon event in a raspberry pi (openplotter) environment. In particular with 'hold values' set to 'on' a dropped wifi-connection will pass completely unnoticed.

side note: I assume, setting LED-flash in mode 'bus data' also refers to internal bus of OBP60, correct?

**Comment by W-Geronius** [comment]
I will further explore this issue, as under certain (rare?) circumstances, the LED in fact flashes and message 'no GPS data' is shown even if internal GPS is set to 'off'.

**Comment by W-Geronius** [comment]
From what I found, LED flash mode 'GPS fix lost' seems to be solely triggered by the GPSD and GPST.

![CAPT-20241010-132620](https://github.com/user-attachments/assets/db133c3f-de2c-4916-835d-ab1694222e53)

The LED will never flash whenever GPSD and GPST are present, irrespective of GPS fix

**Comment by W-Geronius** [comment]
fixed by latest commit
