### ISSUE TITLE
Hardware: inconsistency of exported files

### ISSUE THREAD

**Issue by speters** [norbert-walter/esp32-nmea2000-obp60#99]
As the [docu-project](https://github.com/norbert-walter/obp60-v2-docu/) has no issue tracker:

Export of [BOM_OBP60_V2.1.txt](https://github.com/norbert-walter/obp60-v2-docu/blob/main/docs/_static/files/BOM_OBP60_V2.1.txt) and its interactive variant [ibom_multifunktionsdisplay_V2.1.html](https://obp60-v2-docu.readthedocs.io/de/latest/_static/files/ibom_multifunktionsdisplay_V2.1.html) do not match.

There is also a revision mismatch between the interactive bom (which states "Rev: 2024-10-08 15:24:08") and the schematics (showing "2023-07-26").

PS:
KiCAD is able to import EasyEDA files, no need to rely on closed cloud software.

**Comment by norbert-walter** [comment]
Where are there inconsistencies? HTML-BOM was derived from the current project.

I will set up an issue area for the documentation.

**Comment by norbert-walter** [comment]
I add the issue tracker

**Comment by speters** [comment]
TXT BOM lists 52 different parts, HTML BOM has 83.

If you start looking: C8, C11, C29, C30, C7, C10, C43, C9, C44, C5, C14, C42, R1, R12, R18, R22, R11, R5, R7, R23, R25, D9, ... 

It's not just changed references.

PS:
You can [transfer issues to another project](https://docs.github.com/en/issues/tracking-your-work-with-issues/administering-issues/transferring-an-issue-to-another-repository).

**Comment by norbert-walter** [comment]
Ahh... Nice to know.

**Comment by norbert-walter** [comment]
I found the error. The TXT list has onlx the parts from the top side. Bottom side is missing. I fix it.

**Comment by norbert-walter** [comment]
Fixed in actual docu.
